### PR TITLE
Update meeting_minutes.txt

### PR DESCRIPTION
**Pull request by PK-SS**

### CODE REVIEW

**Comment by elecclubiitg** [comment]
Ohhhooo such prompt commit! Bohot hi badhiya. 

Bas you used the lab bench power supply to power the solenoid lock, not the Multimeter

**Comment by PK-SS** [comment]
Yes bhaiya

**Comment by elecclubiitg** [comment]
Tum toh chatting hi karne lage yaha pe. 😂

**Comment by PK-SS** [comment]
Lol 😂

**Pull request merged**
